### PR TITLE
Creating Folder for some S-H Notes

### PR DESCRIPTION
**Pull request by MatthewRGonzalez**
I want to include some additional information that I developed while coding S-H. I organized these items in a folder for ease of access. The README file within this folder describes each file. 

- The Jan_20th Report has many small details/thoughts, and was developed while working through complicated entries. There are many instances that have since been resolved. 
- "GonzalezM_Development of descriptions" logs any instance where I had to tweak original description entries to accommodate changes across rounds. This file also outlines how I made these decisions. 
- "Best-Guesses" is still in development.  (More in the README.md)

### CODE REVIEW

**Comment by kbuzard** [comment]
Wow, this represents a LOT of careful work. I should read over these files carefully, but I'm not sure now is the best time for me to do that. What do you think @MatthewRGonzalez

**Comment by MatthewRGonzalez** [comment]
I don't feel that theres a rush for you to review these files. I'll just note that I intend to spend some time working through entries of the "Best Guesses" file. I felt uneasy about some of these lines, but didn't think were as difficult as the complicated paragraphs mentioned in #61. 

If you'd like me to close this and submit a PR at a more appropriate time I can do so- or whatever best suits your workflow

**Comment by kbuzard** [comment]
How about this: take this pull request back and make one with those files that are no longer actively in process. Then make another pull request when the other file(s) are at a place where either my feedback could be useful or there's something important you think I can learn for guiding the analysis.

**Comment by MatthewRGonzalez** [comment]
This sounds good. Closing this PR and I'll decide tomorrow on what will be most valuable to commit- Thanks!

**Pull request closed without merging**
