### PR TITLE
Create data_cleaning_revised.r

### PR DESCRIPTION
**Pull request by Zeyuan-Xiong**
I propose the above revised code to clean the data. The step is the same, download a latest copy from OneDrive, save as UTF-8 csv file and run the code. Altogether 6 cloumns are added: "header"_1946_before, and "header"_1946_after. In short names they are denoted as SB and SA in the summary statistics. 

PS: The increase you can see in the summary stats of Sp between SB and SA should be related to tax intervals, some specific tax rates are removed and thus has a smaller denominator, increases the mean value.

### CODE REVIEW

**Comment by kbuzard** [comment]
I downloaded this code and was able to run it, so already that's great. I have a few questions/comments:
1. This code is much more compact and easy to understand! After the CEAs, I will see if I can write something more compact for lines 38-210. There is probably a more elegant way to write the function f_replace too, but I don't think that's as important because it's not too hard to see what's going on.
2. the kable_extra package was missing; I added it in the version I have locally.
1. You said you added six columns, I'm assuming you mean three each for 1946_before and 1946_after. Is that right?
2. What do 1946_before and 1946_after actually mean? It looks like the "before" is maybe just a re-listing of Smoot Hawley that you found in the 1946 document and re-entered. And I would assume the "after" is what the tariffs actually were in 1946.
3. I don't understand why the summary stats that are produced now are so drastically different across many schedules from the last version I had run on the old data. Is this all about the tax intervals thing you mentioned, or could something else be going on? Below are (first) a screenshot of the relevant table that I compiled a few days ago on the previous data and then (second) what was produced when I ran this new code on the new data in Schedules_1-15_units_changed_HS - corrected.xlsx as of 5/5/21.

image

image

**Comment by Zeyuan-Xiong** [comment]
1. That is great, thank you!
2. Yeah, I guess I run the package before testing the code, thanks for adding it.
3. Yes, that is correct, and there is another column "Extra_1946" which is not included in the code, just like other "extra" columns.
4. For notation convenience, I simply set the year 1946 as the benchmark year, assuming that all the tax rate changes happened in year 1946 (but they are not actually), so this might be a little misleading. Based on the stats and the file documentation, we can see the "before" as the same rate as original S-H, and the "after" as the rate of US in year 1946. Altough for some products, multiple periods of tax rate changes took place (during multiple bilateral trade agreements), we only documented the final tax rate in 1946.
5. I am checking the code, I might propose some changes later in the pull request with respective to the table part, thanks for the reminder!

**Comment by Zeyuan-Xiong** [comment]
I corrcted some typos in the last chunk of table contents. I did not find any significant errors with repsect to the codes yet.

After correction. The new generated table is still different from the old one, but I believe the most difference is in the schedule 1 stats. I do remember I made several changes in the chemical schedules when doing concordance, both in Geneve 47 and in SH, so that might be the reason. The stats are very similar for other schedules and rounds, so I think that might be the reason. But I will keep an eye on this, please let me know if you see any irregular lines or result when going through your codes for analysis.

**Comment by Zeyuan-Xiong** [comment]
Also as for the "tax interval issues", if we compare the "-1946 after" column with the "Geneva47" columns, much less lines are involved with this issue, namely many tax interval changes happened before Geneva47. Instead of the "interval column", I think we can just use the "which" function to identify those lines, should be much easier.

**Comment by kbuzard** [comment]
On #4: I ran a quick check that shows that every line in the 1946_before column is exactly the same as Smoot Hawley. That seems to agree with what you said. If so, I think it would be better for analysis purposes to not have those three columns in the cleaned data.

On #5: I was most concerned about the changes in Schedule 1. I've run the table that takes out the interval lines, and that increase in tariffs doesn't go away. Would you look into what's going on with Schedule 1?

Can you explain more concretely what you meant by "Instead of the "interval column", I think we can just use the "which" function to identify those lines, should be much easier."?

**Comment by kbuzard** [comment]
I have integrated the code into data_cleaning.r . So I won't merge this pull request, but I'm not going to close it until we've finished our conversation.

**Comment by Zeyuan-Xiong** [comment]
I have identified the major reason for the dramtical changes in schedule 1: I believe Matt has mis-entered three lines in the "Specific_1946_before column" : line: 280, 281, 282. These three products (opium) have very large units (dollars), which means single mistake will have large impacts for the mean. Since the Geneva round and Annecy round are empty for those lines, they inherit the tax level in "Specific_1946_before column", this reflects in the picture you attached that after Torquay round, the difference is not significant. I have corrected these three lines and the result is closer to what we used to have.

**Comment by Zeyuan-Xiong** [comment]
Further, explanation for the relatively slight differences across all schedules: 

(1) We did make some changes in tax rates in the past two month during concordance work and 1946 work, but not many.
(2) Since our code will let the empty lines to inherit the previous round tax rate if they are empty, many of Geneva47 and Annecy lines will inherit the "1946_before" tax rate instead of the original S-H tax rate.

Therefore, on average, we will expect the new table will have relative low values in Geneva47 and Annecy columns. These changes reflected in the summary stat are relatively small. The schedule is a special case since those three lines are entered like 10 times larger in value and themselves have dollar units which in end leads to large bias.

**Comment by Zeyuan-Xiong** [comment]
Sorry that I made a mistake in the comments above, please take all the "1946_before" columns as "1946_after columns". I was referring to the lines (columns) right before Geneva47 and already have some level of tax reduction after S-H.

Sorry for the inconvenience and confusion it brings!

**Comment by kbuzard** [comment]
Okay, I'm going to close this pull request now. Will you email me with what you meant by "Instead of the "interval column", I think we can just use the "which" function to identify those lines, should be much easier"

**Pull request closed without merging**
